config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  resources :users, only: [:show, :edit, :update] do
    # Add a custom route to handle updating individual fields
    # Other member routes...
  end

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :projects
  # get 'search', to: 'projects#index'

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ]
  # using: {
  #   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  # }

  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :project_skills, dependent: :destroy
  has_many :skills, through: :project_skills
  has_one :chatroom, dependent: :destroy
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_and_belongs_to_many :users, through: :user_skills
  has_many :project_skills, dependent: :destroy
  has_many :projects, through: :project_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :projects, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :photo

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split[1..-1].join(" ")
      user.github_link = auth.info.urls.GitHub
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["name"].split.first if user.first_name.blank?
        user.last_name = data["name"].split[1..-1].join(" ") if user.last_name.blank?
        user.github_link = data["urls"]["GitHub"] if user.github_link.blank?
      end
    end
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatrooms = policy_scope(Chatroom)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    authorize @chatroom
    @message = Message.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @user_projects = @user.projects.includes(:skills).order(created_at: :desc)
    @user_skills = @user.skills
    authorize @user
  end

  def edit
    @user = current_user
    @skills = Skill.all
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :job_title, :about_me, :github_link, :photo, skill_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_skills_helper.rb
module ProjectSkillsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/index.html.erb
<div class="container">
  <h1 class="mb-5">Chatrooms</h1>

  <% @chatrooms.each do |chatroom| %>
    <%= link_to chatroom_path(chatroom) do %>
      <div class="chatroom">
        <h2><%= chatroom.project.name %></h2>
        <h5>Description: <%= chatroom.project.description %></h5>

        <% if chatroom.messages[-3] %>
        <p><em><%= chatroom.messages[-3].user.first_name %>:</em> <%= chatroom.messages[-3].content %></p>
        <% end %>

        <% if chatroom.messages[-2] %>
        <p><em><%= chatroom.messages[-2].user.first_name %>:</em> <%= chatroom.messages[-2].content %></p>
        <% end %>

        <% if chatroom.messages.last %>
        <p><strong><em><%= chatroom.messages.last.user.first_name %>:</em> <%= chatroom.messages.last.content %></strong></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1 class="mb-3">Chatroom</h1>
  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
  <%= simple_form_for [@chatroom, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
%>
    <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.project.name}",
    wrapper_html: {class: "flex-grow-1"}
  %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>