config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  resources :users, only: [:show, :edit, :update] do
    # Add a custom route to handle updating individual fields
    # Other member routes...
  end

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :projects
  # get 'search', to: 'projects#index'

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ]
  # using: {
  #   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  # }

  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :project_skills, dependent: :destroy
  has_many :skills, through: :project_skills
  has_one :chatroom, dependent: :destroy
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_and_belongs_to_many :users, through: :user_skills
  has_many :project_skills, dependent: :destroy
  has_many :projects, through: :project_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :projects, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :photo

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split[1..-1].join(" ")
      user.github_link = auth.info.urls.GitHub
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["name"].split.first if user.first_name.blank?
        user.last_name = data["name"].split[1..-1].join(" ") if user.last_name.blank?
        user.github_link = data["urls"]["GitHub"] if user.github_link.blank?
      end
    end
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :github

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @user_projects = @user.projects.includes(:skills).order(created_at: :desc)
    @user_skills = @user.skills
    authorize @user
  end

  def edit
    @user = current_user
    @skills = Skill.all
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :job_title, :about_me, :github_link, :photo, skill_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_skills_helper.rb
module ProjectSkillsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_photo.html.erb
<h1>Edit Your Profile Photo</h1>

<%= form_with(model: @user, url: update_photo_user_path(@user), method: :patch, local: true, multipart: true) do |form| %>
  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, as: :file, label: false, required: false %>
  </div>

  <div class="actions">
    <%= form.submit "Update Photo" %>
  </div>
<% end %>

<%= link_to "Back to Profile", user_path(@user) %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<div class="container-user-basic-info">
  <h1 class="red-header">
    <%= @user.first_name %>
    <%= @user.last_name %>
  </h1>
  <%= link_to raw('<i class="fa-solid fa-pen-to-square"></i>'), edit_user_registration_path(@user) %>
  <h5 class="black-subheader-bold">
    <%= @user.job_title %>
  </h5>
  <div class="user-profile-github">
    <%= link_to raw('<i class="fab fa-github"></i>'), @user.github_link, target: '_blank' %>
  </div>
</div>

<div class="user-profile-image"></div>

<div class="container-user-about">
  <h5 class="black-subheader-bold">
    About me
  </h5>
  <br>
  <p>
    <%= @user.about_me %>
  </p>
</div>

<div class="container-user-profile-skills">
  <h5 class="black-subheader-bold">
    Skills
  </h5>
  <% if @user.user_skills.nil? %>
    <%= simple_form_for @user do |f| %>
      <div class="d-flex flex-wrap" data-controller="skills">
        <%= f.collection_check_boxes :skill_ids, @skills, :id, :technology do |b| %>
          <span class="ms-5 me-5 mt-3 mb-3 d-flex justify-content-center align-items-center container-skill <%= "selected-skill" if @user.skill_ids.include?(b.value) %>"
            data-target="skillName" data-action="click->skills#toggleHighlight">
            <%= b.check_box + b.text %>
          </span>
        <% end %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Update", class: "primary-button-medium" %>
      </div>
    <% end %>

  <% else %>
    <div class="container-user-skills">
      <% @user.skills.each do |skill| %>
        <div class="container-skill">
          <%= skill.technology %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container-user-profile-projects">
  <h5 class="black-subheader-bold">
    Projects
  </h5>
  <div class="container-user-projects">
    <% @user.projects.each do |project| %>
      <div class="card-user-project">
        <div class="card-user-project-title">
          <h4 class="red-subheader">
            <%= project.name %>
          </h4>
          <p class="black-text-bold">
            <%= project.user.first_name %>
            <%= project.user.last_name %>
          </p>
        </div>
        <div class="card-user-project-skills">
          <% project.skills.each do |skill| %>
            <div class="container-skill-sm">
              <%= skill.technology %>
            </div>
          <% end %>
        </div>
        <%= link_to "See more", project_path(project), class: "button-signup" %>
      </div>
    <% end %>
  </div>
</div>