config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  resources :users, only: [:show, :edit, :update] do
    # Add a custom route to handle updating individual fields
    # Other member routes...
  end

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :projects
  # get 'search', to: 'projects#index'

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ]
  # using: {
  #   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  # }

  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :project_skills, dependent: :destroy
  has_many :skills, through: :project_skills
  has_one :chatroom, dependent: :destroy
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_and_belongs_to_many :users, through: :user_skills
  has_many :project_skills, dependent: :destroy
  has_many :projects, through: :project_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :projects, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :photo

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split[1..-1].join(" ")
      user.github_link = auth.info.urls.GitHub
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["name"].split.first if user.first_name.blank?
        user.last_name = data["name"].split[1..-1].join(" ") if user.last_name.blank?
        user.github_link = data["urls"]["GitHub"] if user.github_link.blank?
      end
    end
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @user_projects = @user.projects.includes(:skills).order(created_at: :desc)
    @user_skills = @user.skills
    authorize @user
  end

  def edit
    @user = current_user
    @skills = Skill.all
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :job_title, :about_me, :github_link, :photo, skill_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railyard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-landing-page">
  <header class="container-header-landing-page">
    <h1 class="title-landing-page">
      Railyard
    </h1>
    <h4 class="subtitle-landing-page">
      Build the Rails way together.
    </h4>
    <a href="/projects" class="button-landing-page">
      Get started <i class="fa-solid fa-arrow-right"></i>
    </a>
  </header>
</div>

<div class="container-home">
  <div id="connect" data-controller="scroll-reveal">
    <h1 class="title-home-page">
      Connect with other Rails developers
    </h1>
  </div>
  <div id="build" data-controller="scroll-reveal">
    <h1 class="title-home-page">
      Build projects together
    </h1>
  </div>
  <div id="showcase" data-controller="scroll-reveal">
    <h1 class="title-home-page">
      Showcase your work
    </h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% unless controller_name == "pages" && action_name == "home" %>
  <nav class="navbar d-flex justify-content-between align-items-center p-0 border-bottom">
    <div class="navbar-container-left d-flex justify-content-start align-items-center">
      <%# <a href class= "navbar-title">
        Railyard
      </a> %>
      <%= link_to "Railyard", root_path, class: "navbar-title" %>
      <div class="search-bar">
        <%= form_with url: projects_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for a Rails Project"
        %>
    <% end %>
      </div>
    </div>
    <div class="navbar-container-right d-flex justify-content-end align-items-center pe-5">
      <% if current_user %>
        <div class="d-flex justify-content-around align-items-center w-25">
          <div class="new-project-icon">
            <%= link_to '<i class="fa-solid fa-plus"></i>'.html_safe, new_project_path %>
          </div>
          <div class="message-notifications-icon">
            <%= link_to chatrooms_path do %>
              <i class="fa-solid fa-comments"></i>
            <% end %>
          </div>
          <div class="nav-user-profile">
            <%= link_to raw('<i class="fa-solid fa-circle-user"></i>'), user_path(current_user) %>
          </div>
        </div>
      <% else %>
        <%= button_to "Login", new_user_session_path, data: { turbo: false }, class: "button-login" %>
        <a href="/users/sign_up" class="button-signup">Sign up</a>
      <% end %>
    </div>
  </nav>
<% else %>
  <nav class="navbar-landing-page">
    <%= button_to "Login", new_user_session_path, data: { turbo: false }, class: "button-login" %>
    <a href="/users/sign_up" class="button-signup">Sign up</a>
  </nav>
<% end %>