config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  resources :users, only: [:show, :edit, :update] do
    # Add a custom route to handle updating individual fields
    # Other member routes...
  end

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :projects
  # get 'search', to: 'projects#index'

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ]
  # using: {
  #   tsearch: { prefix: true } # <-- now `superman batm` will return something!
  # }

  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :project_skills, dependent: :destroy
  has_many :skills, through: :project_skills
  has_one :chatroom, dependent: :destroy
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_and_belongs_to_many :users, through: :user_skills
  has_many :project_skills, dependent: :destroy
  has_many :projects, through: :project_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :projects, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :photo

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split[1..-1].join(" ")
      user.github_link = auth.info.urls.GitHub
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["name"].split.first if user.first_name.blank?
        user.last_name = data["name"].split[1..-1].join(" ") if user.last_name.blank?
        user.github_link = data["urls"]["GitHub"] if user.github_link.blank?
      end
    end
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
require 'date'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    authorize Project
    @projects = policy_scope(Project)
    if params[:query].present?
      @projects = Project.search_by_name_and_description(params[:query])
    else
      @projects = Project.all
    end
  end

  def show
    @hours = posted_hours_ago(@project.created_at)
    @sent_request = current_user.requests.find_by(project_id: @project.id) if current_user
    authorize @project
  end

  def new
    @skills = Skill.all
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @skills = Skill.all
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    authorize @project
    redirect_to projects_path, show: :see_other
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def posted_hours_ago(created_at)
    time_difference = (Time.now - created_at).to_i
    (time_difference / 1.hour).to_i
  end

  def project_params
    params.require(:project).permit(:name, :description, :amount_of_people, :repo_link, skill_ids: [])
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @user_projects = @user.projects.includes(:skills).order(created_at: :desc)
    @user_skills = @user.skills
    authorize @user
  end

  def edit
    @user = current_user
    @skills = Skill.all
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :job_title, :about_me, :github_link, :photo, skill_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_skills_helper.rb
module ProjectSkillsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/edit.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name,
              hint: "leave it blank if you don't want to change it" %>
  <%= f.input :description,
              hint: "leave it blank if you don't want to change it" %>
  <%= f.input :amount_of_people,
              hint: "leave it blank if you don't want to change it" %>
  <%= f.input :repo_link,
              hint: "leave it blank if you don't want to change it" %>
  <label>Skills</label>
  <div class="d-flex flex-wrap" data-controller="skills">
    <%= f.collection_check_boxes :skill_ids, @skills, :id, :technology do |b| %>
      <span class="ms-5 me-5 mt-3 mb-3 d-flex justify-content-center align-items-center container-skill <%= "selected-skill" if @project.skill_ids.include?(b.value) %>"
       data-target="skillName" data-action="click->skills#toggleHighlight">
        <%= b.check_box + b.text %>
      </span>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Update", class: "primary-pill-button-medium" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="d-flex p-4">
  <div class="side-menu-section text-center p-3"><div class="side-menu"></div></div> <%# side-menu %>

  <div class="cards-section d-flex flex-column ps-4 pe-4"> <%# cards-section %>
    <% @projects.each do |project| %>
      <div class="project-card d-flex mt-4 mb-4 border"> <%# project-card %>
        <div class="card-user d-flex flex-column align-items-center justify-content-center ms-3 mt-2 mb-2"> <%# card-user %>
          <a href="/users/<%= project.user.id %>"><img class="avatar-medium mb-2" src="https://images.pexels.com/photos/2586823/pexels-photo-2586823.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="User profile image"></a> <%# Placeholder for the user profile image %>
          <div class="text-center">
            <a href="/users/<%= project.user.id %>"><%= project.user.first_name %> <%= project.user.last_name %></a>
          </div>
        </div>
        <div class="d-flex flex-column justify-content-center flex-grow-1 ms-3 me-3 p-2 pt-4 pb-4"> <%# card-info %>
          <div class="d-flex mb-2"> <%# info-header %>
            <div class="d-flex align-items-center"><h1 class="m-0"><h1><%= link_to project.name, project_path(project) %></h1></div>
            <div class="d-flex justify-content-around align-items-center flex-grow-1"> <%# skills-section %>
              <% project.skills.each do |skill| %>
                <span class="skill text-center"><%= skill.technology %></span>
              <% end %>
            </div>
          </div>
          <div><%= project.description %></div> <%# info-body %>
          <%#= project.amount_of_people %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :amount_of_people %>
  <%= f.input :repo_link %>
  <label>Skills</label>
  <div class="d-flex flex-wrap" data-controller="skills">
    <%= f.collection_check_boxes :skill_ids, @skills, :id, :technology do |b| %>
      <span class="ms-5 me-5 mt-3 mb-3 d-flex justify-content-center align-items-center container-skill"
       data-target="skillName" data-action="click->skills#toggleHighlight">
        <%= b.check_box + b.text %>
      </span>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Create", class: "primary-pill-button-medium" %>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="container p-5">
  <div class="d-flex"> <%# project-header %>
    <div class="header-left-section d-flex flex-column justify-content-around border-bottom"> <%# header-left-section %>
      <p class="m-0 ps-5 pe-5 pb-4 pt-4"><%= link_to '<i class="fa-solid fa-arrow-left-long"></i>'.html_safe, :back, class: "me-3" %> <span>Projects</span> / <span , class= "fw-bold"><%= @project.name %></span></p>
      <h1 class="ps-5 pe-5 m-0"><%= @project.name %></h1>
      <div class="ps-5 pe-5 pt-4 pb-4">
        <span class="me-3"><i class="fa-solid fa-user"></i> <%= @project.amount_of_people %></span>
        <span class="me-3">Posted by
          <% if (current_user && @project.user.first_name != current_user.first_name) || current_user.nil? %>
            <a href="/users/<%= @project.user.id %>" class="underlined-bold-text"><%= @project.user.first_name %> <%= @project.user.last_name %></a>
          <% elsif current_user && @project.user.first_name == current_user.first_name %>
            <a href="/users/<%= @project.user.id %>" class="underlined-bold-text">You</a>
          <% end %>
          <%= @hours %> <%= "hour".pluralize(@hours) %> ago
        </span>
        <% if @project.user == current_user %>
          <span>
            <%= link_to '<i class="fa-solid fa-pen-to-square"></i>'.html_safe, edit_project_path(@project), class: "me-2" %>
            <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, project_path(@project), data: { turbo_method: :delete } %>
          </span>
        <% end %>
      </div>
    </div>
    <% if signed_in? %> <%# header-right-section %>
      <div class="header-right-section border-bottom d-flex justify-content-center align-items-center">
        <% if @sent_request && @sent_request.status == "accepted"%>
          <div class="d-flex justify-content-around align-items-center">
            <span class="me-2"><%= link_to '<i class="fa-brands fa-github"></i>'.html_safe, "#" %></span>
            <span><%= link_to "Chatroom", "#", class: "primary-pill-button-medium" %></span>
            <span class="ms-2"><%= link_to "Joined", "#", class: "primary-pill-button-medium reverse-primary-button"%></span>
          </div>
        <% elsif @sent_request && @sent_request.status == "pending" %>
          <div><%= link_to "Pending", "#",class: "primary-pill-button-large reverse-primary-button"%></div>
        <% elsif @sent_request.nil? %>
          <%= link_to "Join", "#", class: "primary-pill-button-large"%>
          <%# <div data-controller="requests" %>
              <%# data-request-project-id="<%= @project.id"
              <%# data-request-csrf-token="<%= form_authenticity_token "
              <%# data-request-user-id="<%= current_user.id ">
            <%= link_to "Join", new_project_request_path(@project), class: "primary-pill-button-large", data: { action: "click->requests#createRequest" }
            <div data-target="response"></div>
          </div> %>
        <% end %>
      </div>
    <% else %>
      <div class="header-right-section">
        <div class="sign-up text-center">
          <h2>Ready to collaborate?</h2>
          <%= link_to "Sign up", new_user_registration_path, class: "button-signup" %>
          <div>
            <span>Already have an account? </span>
            <%= link_to "Login", new_user_session_path, class: "fw-bold" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="border-bottom p-5"> <%# project-body %>
    <p class="m-0"><%= @project.description %></p>
  </div>
  <div class="p-5"> <%# project-footer %>
    <p class="fw-bold mb-4">Skills</p>
    <div class="d-flex justify-content-around align-items-center flex-grow-1">
      <% @project.skills.each do |skill| %>
        <span class="container-skill text-center"><%= skill.technology %></span>
      <% end %>
    </div>
  </div>
</div>